package com.mustafafyp.guardianai.ai;

/**
 * Min/Max normalization constants from the MinMaxScaler used during training.
 *
 * Generated by running the Python scaler helper snippet on guardian_scaler.pkl
 * after training on the Kaggle Screen Time & App Usage dataset.
 *
 * DO NOT manually edit these values — re-run the Python snippet if you retrain.
 */
public class FeatureNormConstants {

    // screen_time_min
    public static final float SCREEN_TIME_MIN_MIN = 0.0100f;
    public static final float SCREEN_TIME_MIN_MAX = 218.3900f;

    // launches
    public static final float LAUNCHES_MIN = 0.0000f;
    public static final float LAUNCHES_MAX = 9.0000f;

    // interactions
    public static final float INTERACTIONS_MIN = 0.0000f;
    public static final float INTERACTIONS_MAX = 13.0000f;

    // is_productive
    public static final float IS_PRODUCTIVE_MIN = 0.0000f;
    public static final float IS_PRODUCTIVE_MAX = 1.0000f;

    // youtube_views
    public static final float YOUTUBE_VIEWS_MIN = 0.0000f;
    public static final float YOUTUBE_VIEWS_MAX = 494839.0000f;

    // youtube_likes
    public static final float YOUTUBE_LIKES_MIN = 0.0000f;
    public static final float YOUTUBE_LIKES_MAX = 43893.0000f;

    // youtube_comments
    public static final float YOUTUBE_COMMENTS_MIN = 0.0000f;
    public static final float YOUTUBE_COMMENTS_MAX = 8934.0000f;

    // extra_col_11
    public static final float EXTRA_COL_11_MIN = 14.6500f;
    public static final float EXTRA_COL_11_MAX = 85.8200f;

    // extra_col_12
    public static final float EXTRA_COL_12_MIN = 13.1700f;
    public static final float EXTRA_COL_12_MAX = 81.7400f;

    // extra_col_13
    public static final float EXTRA_COL_13_MIN = 11.7300f;
    public static final float EXTRA_COL_13_MAX = 83.3300f;

    // extra_col_14
    public static final float EXTRA_COL_14_MIN = 13.9500f;
    public static final float EXTRA_COL_14_MAX = 84.3800f;

    // extra_col_15
    public static final float EXTRA_COL_15_MIN = 11.0100f;
    public static final float EXTRA_COL_15_MAX = 78.0500f;

    // extra_col_16
    public static final float EXTRA_COL_16_MIN = 13.2000f;
    public static final float EXTRA_COL_16_MAX = 92.5200f;

    // extra_col_17
    public static final float EXTRA_COL_17_MIN = 13.8600f;
    public static final float EXTRA_COL_17_MAX = 92.4800f;

    // extra_col_18
    public static final float EXTRA_COL_18_MIN = 16.8800f;
    public static final float EXTRA_COL_18_MAX = 84.8900f;

    // extra_col_19
    public static final float EXTRA_COL_19_MIN = 18.2300f;
    public static final float EXTRA_COL_19_MAX = 85.0900f;

    // extra_col_20
    public static final float EXTRA_COL_20_MIN = 15.0100f;
    public static final float EXTRA_COL_20_MAX = 86.1000f;

    // extra_col_21
    public static final float EXTRA_COL_21_MIN = 20.0400f;
    public static final float EXTRA_COL_21_MAX = 84.9500f;

    // extra_col_22
    public static final float EXTRA_COL_22_MIN = 12.1700f;
    public static final float EXTRA_COL_22_MAX = 80.8100f;

    // extra_col_23
    public static final float EXTRA_COL_23_MIN = 15.9100f;
    public static final float EXTRA_COL_23_MAX = 84.8000f;

    // DayOfWeek (0=Monday … 6=Sunday)
    public static final float DAYOFWEEK_MIN = 0.0000f;
    public static final float DAYOFWEEK_MAX = 6.0000f;

    // DayOfMonth (1–31)
    public static final float DAYOFMONTH_MIN = 1.0000f;
    public static final float DAYOFMONTH_MAX = 31.0000f;

    // IsWeekend (0 or 1)
    public static final float ISWEEKEND_MIN = 0.0000f;
    public static final float ISWEEKEND_MAX = 1.0000f;

    // Category one-hot encodings (0 or 1)
    public static final float CAT_ENTERTAINMENT_MIN = 0.0000f;
    public static final float CAT_ENTERTAINMENT_MAX = 1.0000f;

    public static final float CAT_PRODUCTIVITY_MIN = 0.0000f;
    public static final float CAT_PRODUCTIVITY_MAX = 1.0000f;

    public static final float CAT_SOCIAL_MIN = 0.0000f;
    public static final float CAT_SOCIAL_MAX = 1.0000f;

    public static final float CAT_UTILITIES_MIN = 0.0000f;
    public static final float CAT_UTILITIES_MAX = 1.0000f;
}
